export const cardsMock = [
  {
    id: 1,
    name: 'Nubank',
    brand: 'Mastercard',
    limitCredit: 400.0,
    credito: 114.65,
    debit: 0.0,
    color: '#530082',
    datePayment: '14/11/2022',
    namePropiety: 'Daniel Ferraz Coelho',
  },
  {
    id: 2,
    name: 'Nubank',
    brand: 'Mastercard',
    limitCredit: 400.0,
    credito: 307.64,
    debit: 0.0,
    color: '#530082',
    datePayment: '14/11/2022',
    namePropiety: 'Maria Tereza Gomes Rodrigues',
  },
  {
    id: 3,
    name: 'PicPay',
    brand: 'Mastercard',
    limitCredit: 400.0,
    credito: 35.16,
    debit: 0.0,
    color: '#202024',
    datePayment: '25/11/2022',
    namePropiety: 'Daniel Ferraz Coelho',
  },
  {
    id: 4,
    name: 'Next',
    brand: 'Visa',
    limitCredit: 1900.0,
    credito: 136.31,
    debit: 0.0,
    color: '#00ff5f',
    datePayment: '14/11/2022',
    namePropiety: 'Daniel Ferraz Coelho',
  },
  {
    id: 5,
    name: 'Iti',
    brand: 'Visa',
    limitCredit: 1300.0,
    credito: 64.16,
    debit: 0.0,
    color: '#FE3386',
    datePayment: '27/11/2022',
    namePropiety: 'Daniel Ferraz Coelho',
  },
  {
    id: 6,
    name: 'Iti',
    brand: 'Visa',
    limitCredit: 50.0,
    credito: 32.12,
    debit: 0.0,
    color: '#FE3386',
    datePayment: '27/11/2022',
    namePropiety: 'Maria Tereza Gomes Rodrigues',
  },
  {
    id: 7,
    name: 'Neon',
    brand: 'Visa',
    limitCredit: 500.0,
    credito: 56.51,
    debit: 0.0,
    color: '#0f92ff',
    datePayment: '14/11/2022',
    namePropiety: 'Daniel Ferraz Coelho',
  },
];

export const cardsFilter = [
  {
    id: 1,
    name: 'Nubank',
  },
  {
    id: 2,
    name: 'PicPay',
  },
  {
    id: 3,
    name: 'Neon',
  },
  {
    id: 4,
    name: 'Iti',
  },
  {
    id: 5,
    name: 'Next',
  },
];

export const CategoryMock = [
  {
    id: 1,
    name: 'Alimentação',
  },
  {
    id: 2,
    name: 'Bebidas',
  },
  {
    id: 3,
    name: 'Estética',
  },
  {
    id: 4,
    name: 'Saúde',
  },
  {
    id: 5,
    name: 'Viagens',
  },
  {
    id: 6,
    name: 'Roupas',
  },
  {
    id: 7,
    name: 'Supermercado',
  },
];

export const dataTransactionsMock = [
  {
    id: 1,
    name: 'Supermercado Oliveira ',
    category: 'Supermercado',
    value: 47.5,
    date: '01/05/2022',
    card_id: 1,
  },
  {
    id: 2,
    name: 'Supermecado Gabriele',
    category: 'Supermercado',
    value: 47.5,
    date: '15/10/2022',
    card_id: 3,
  },
  {
    id: 3,
    name: 'Restaurante Vovó Bela',
    category: 'Alimentação',
    value: 47.5,
    date: '21/05/2022',
    card_id: 4,
  },
  {
    id: 4,
    name: 'Jô Fashion',
    category: 'Roupas',
    value: 47.5,
    date: '16/10/2022',
    card_id: 6,
  },
  {
    id: 5,
    name: 'Mercearia El Shaday',
    category: 'Roupas',
    value: 47.5,
    date: '17/10/2022',
    card_id: 6,
  },
  {
    id: 6,
    name: 'Farmacia Santa Maria',
    category: 'Saúde',
    value: 28.0,
    date: '17/10/2022',
    card_id: 6,
  },
  {
    id: 7,
    name: 'Cervejas Bar',
    category: 'Bebidas',
    value: 47.5,
    date: '17/10/2022',
    card_id: 6,
  },
  {
    id: 8,
    name: 'Bar meia noite',
    category: 'Bebidas',
    value: 47.5,
    date: '17/10/2022',
    card_id: 6,
  },
  {
    name: 'Hotel Milla',
    category: 'Viagens',
    value: 260.89,
    date: '01/02/2022',
    card_id: 5,
    id: 9,
  },
  {
    name: 'Hotel Chauan',
    category: 'Viagens',
    value: 260.89,
    date: '23/08/2021',
    card_id: 1,
    id: 10,
  },
  {
    name: 'Hospital Sobrasa',
    category: 'Saúde',
    value: 760.89,
    date: '03/04/2022',
    card_id: 5,
    id: 11,
  },
  {
    name: 'Hospital dos óculos',
    category: 'Estética',
    value: 260.89,
    date: '01/02/2022',
    card_id: 1,
    id: 12,
  },
  {
    name: 'Viagem Eunápolis',
    category: 'Viagens',
    value: 49.59,
    date: '22/04/2022',
    card_id: 5,
    id: 13,
  },
  {
    name: 'Viagem Santa Maria Eterna',
    category: 'Viagens',
    value: 24.12,
    date: '22/04/2022',
    card_id: 1,
    id: 15,
  },

  {
    name: 'Minas Calçados',
    category: 'Roupas',
    value: 24.12,
    date: '04/06/2022',
    card_id: 5,
    id: 16,
  },

  {
    name: 'Minato restaurante',
    category: 'Alimentação',
    value: 24.12,
    date: '20/06/2022',
    card_id: 4,
    id: 17,
  },
  {
    name: 'Açouge',
    category: 'Alimentação',
    value: 26.77,
    date: '21/10/2022',
    card_id: 1,
    id: 18,
  },
  {
    name: 'Àgua mineral',
    category: 'Supermercado',
    value: 11.0,
    date: '21/10/2022',
    card_id: 1,
    id: 19,
  },
  {
    name: 'Mercado Oliveira',
    category: 'Supermercado',
    value: 20.54,
    date: '21/10/2022',
    card_id: 4,
    id: 20,
  },
  {
    name: 'Amazon Prime',
    category: 'Assinatura e serviços',
    value: 14.9,
    date: '16/10/2022',
    card_id: 4,
    id: 21,
  },
  {
    name: 'Cabeleleiro',
    category: 'Estética',
    value: 14.9,
    date: '16/10/2022',
    card_id: 5,
    id: 22,
  },
];
